[test] Add timeout for test
T-PLAY/hub pull request #39
Opened 2024-04-10 11:35 UTC by hiergaut

# Pull Request Desription

## Check if you branch history is PR compatible

- Your branch need to be up to date with origin/main
- Update your git repository `git fetch origin` if origin is this remote
- Check format style with the script provided in `scripts/source-format-all.sh`
- You must use clang-format style (github CI version is 11)
- Your proposal must include a commit where the file CHANGELOG is updated (add a line describing the proposed change + PR id, see file for examples). If your contribution is significant, you can also ask to be added to the contributor list in the discussion.
_These checks are enforced by github workflow actions_
_Please refer to the corresponding log in case of failure_

## UPDATE the form below to describe your PR

Please check if the PR fulfills these requirements

- [x] The commit message follows our guidelines (see CONTRIBUTING)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

- **What kind of change does this PR introduce?**
  - [ ] other: set timeout for tests 
  

- **What is the current behavior?** (You can also link to an open issue here)
The test CI can bug with infinite loop.

- **What is the new behavior (if this is a feature change)?**
Set timeout able to exit tests when test is looping.

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

- **Other information**:

2024-04-22 13:24 UTC, hiergaut commented
@nmellado ready for review

2024-04-29 11:43 UTC, hiergaut commented
Ready for review.

2024-05-14 09:19 UTC, nmellado requested changes
Split ccpcheck + clean history

2024-05-16 15:48 UTC, hiergaut commented
Ready to merge

2024-05-21 09:03 UTC, nmellado approved these changes

2024-05-21 11:24 UTC, merged